Repository cloudforet-io/cost-analysis, pull requests merged in 2024-10, with the labels that each got.

#292 Add logic for creating workspace_id `None` value unified cost
  src/spaceone/cost_analysis/model/unified_cost/database.py
  src/spaceone/cost_analysis/service/unified_cost_service.py
Labels: enhancement

#293 ix create unified cost error when workspace_id is None
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
  src/spaceone/cost_analysis/model/unified_cost/database.py
  src/spaceone/cost_analysis/service/unified_cost_service.py
Labels: enhancement

#295 Modify get `is_confirmed` value for aggregation month
  src/spaceone/cost_analysis/manager/unified_cost_job_manager.py
  src/spaceone/cost_analysis/service/unified_cost_service.py
Labels: enhancement

#298 Modify reset data source account option
  src/spaceone/cost_analysis/model/data_source_account/request.py
  src/spaceone/cost_analysis/service/data_source_account_service.py
Labels: enhancement

#300 refactor: optimize query for performance
  src/spaceone/cost_analysis/service/job_service.py
Labels: pass/signedoff

#301 refactor: optimize query for performance
  src/spaceone/cost_analysis/manager/cost_manager.py
  src/spaceone/cost_analysis/service/job_service.py
Labels: pass/signedoff

#302 Fix create unified cost when workspace is None and has v-workspace-id
  src/spaceone/cost_analysis/service/unified_cost_service.py
Labels: bug

#305 Fix typo at exchange data source value
  src/spaceone/cost_analysis/manager/config_manager.py
  src/spaceone/cost_analysis/service/cost_query_set_service.py
  src/spaceone/cost_analysis/service/unified_cost_service.py
Labels: bug

#307 refactor: remove pagination from analyze and stat queries
  src/spaceone/cost_analysis/service/cost_service.py
Labels: pass/signedoff

#308 Fix delete unified cost error
  src/spaceone/cost_analysis/service/unified_cost_service.py
Labels: bug, pass/signedoff
