Repository cloudforet-io/cost-analysis, pull requests merged in 2024-01, with the labels that each got.

#126 Modify cost_query_set apis
  src/spaceone/cost_analysis/manager/cost_query_set_manager.py
  src/spaceone/cost_analysis/model/cost_query_set_model.py
  src/spaceone/cost_analysis/service/cost_query_set_service.py
Labels: enhancement

#127 Add workspace_id at CostQuerySetInfo
  src/spaceone/cost_analysis/info/cost_query_set_info.py
Labels: enhancement

#128 Fix set and remove cache error
  src/spaceone/cost_analysis/manager/cost_manager.py
Labels: bug

#131 Add workspace_id to secret manager when Domain admin register datasource
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/manager/secret_manager.py
  src/spaceone/cost_analysis/service/data_source_service.py
Labels: bug

#133 Fix typo when create job task
  src/spaceone/cost_analysis/manager/data_source_rule_manager.py
  src/spaceone/cost_analysis/manager/job_task_manager.py
Labels: bug

#143 Add data field at Cost, MonthlyCost Model
  src/spaceone/cost_analysis/model/cost_model.py
Labels: enhancement

#144 Add debug code
  src/spaceone/cost_analysis/manager/identity_manager.py
Labels: enhancement

#145 Modify get system token method at scheduler
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
Labels: bug

#146 Add more debug code
  src/spaceone/cost_analysis/manager/job_task_manager.py
  src/spaceone/cost_analysis/service/job_service.py
Labels: enhancement

#147 Inject domain_id when use system token
  src/spaceone/cost_analysis/manager/cost_manager.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/service/cost_service.py
  src/spaceone/cost_analysis/service/job_service.py
Labels: bug

#148 Add cost_data_keys in monthly aggregate sum field
  src/spaceone/cost_analysis/service/data_source_service.py
  src/spaceone/cost_analysis/service/job_service.py
Labels: enhancement

#149 Edit db cost monthly aggregate query
  src/spaceone/cost_analysis/service/job_service.py
Labels: enhancement

#150 Modify aggregated_cost_data for data_keys
  src/spaceone/cost_analysis/service/job_service.py
Labels: enhancement

#152 Add cost report config
  src/spaceone/cost_analysis/interface/grpc/cost_report_config.py
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/model/cost_report_config/request.py
  src/spaceone/cost_analysis/model/cost_report_config/response.py
  src/spaceone/cost_analysis/plugin/data_source/service/cost_service.py
  src/spaceone/cost_analysis/plugin/data_source/service/data_source_service.py
  src/spaceone/cost_analysis/plugin/data_source/service/job_service.py
  src/spaceone/cost_analysis/service/__init__.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
Labels: enhancement

#153 Add cost_report, cost_report_data to app
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/connector/currency_connector.py
  src/spaceone/cost_analysis/connector/smtp_connector.py
  src/spaceone/cost_analysis/error/cost_analysis.py
  src/spaceone/cost_analysis/info/cost_info.py
  src/spaceone/cost_analysis/interface/grpc/__init__.py
  src/spaceone/cost_analysis/interface/grpc/cost_report.py
  src/spaceone/cost_analysis/interface/grpc/cost_report_config.py
  src/spaceone/cost_analysis/interface/grpc/cost_report_data.py
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/manager/cost_report_data_manager.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/email_manager.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/model/cost_report/__init__.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/request.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/model/cost_report_config/__init__.py
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/model/cost_report_data/__init__.py
  src/spaceone/cost_analysis/model/cost_report_data/database.py
  src/spaceone/cost_analysis/model/cost_report_data/request.py
  src/spaceone/cost_analysis/model/cost_report_data/response.py
  src/spaceone/cost_analysis/service/__init__.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
  src/spaceone/cost_analysis/template/cost_report_en.html
  src/spaceone/cost_analysis/template/cost_report_jp.html
  src/spaceone/cost_analysis/template/cost_report_ko.html
Labels: enhancement

#154 build: add pip package jinja2
  pkg/pip_requirements.txt
Labels: enhancement

#155 Add create cost_report scheduler task
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/email_manager.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#156 Modify aggregate cost_report api
  src/spaceone/cost_analysis/interface/grpc/cost_report.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#157 Add cost_report_data apis
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
  src/spaceone/cost_analysis/manager/cost_report_data_manager.py
  src/spaceone/cost_analysis/model/cost_report_data/database.py
  src/spaceone/cost_analysis/model/cost_report_data/request.py
  src/spaceone/cost_analysis/model/cost_report_data/response.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#158 Add cost_report_data analyze api
  src/spaceone/cost_analysis/interface/grpc/cost_report_data.py
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/manager/email_manager.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/model/__init__.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report_data/database.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#159 Modify send cost report email condition
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#160 Modify send cost report link temporay use pat
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#161 Fix typo at email report period
  src/spaceone/cost_analysis/manager/email_manager.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: bug

#162 Add `bank_name` field in CostReport
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/response.py
Labels: enhancement

#163 Fix check workspace error at identity manager
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/model/cost_report_data/request.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: bug

#164 Add template path at setup.py
  src/setup.py
Labels: enhancement

#165 Add exchange rate
  pkg/pip_requirements.txt
  src/spaceone/cost_analysis/connector/currency_connector.py
  src/spaceone/cost_analysis/manager/currency_manager.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#166 Modify url format for get_url api
  pkg/pip_requirements.txt
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: bug, enhancement

#167 Add `currency_date` field at CostReport model
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/response.py
Labels: enhancement

#168 Remove workspace_id parameter at CostReportConfig
  src/spaceone/cost_analysis/model/cost_report_config/request.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
Labels: bug, enhancement

#169 Add default value 'False' for is_last_day when update CostReportConfig
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
Labels: enhancement

#171 Modify get_url api
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#172 Fix type error
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#173 Add language filter at cost report config
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/model/cost_report_config/request.py
  src/spaceone/cost_analysis/model/cost_report_config/response.py
  src/spaceone/cost_analysis/model/cost_report_data/database.py
  src/spaceone/cost_analysis/model/cost_report_data/response.py
Labels: enhancement

#174 Merge with cost-report feature branch
  pkg/pip_requirements.txt
  src/setup.py
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/connector/currency_connector.py
  src/spaceone/cost_analysis/connector/smtp_connector.py
  src/spaceone/cost_analysis/error/cost_analysis.py
  src/spaceone/cost_analysis/info/cost_info.py
  src/spaceone/cost_analysis/interface/grpc/__init__.py
  src/spaceone/cost_analysis/interface/grpc/cost_report.py
  src/spaceone/cost_analysis/interface/grpc/cost_report_config.py
  src/spaceone/cost_analysis/interface/grpc/cost_report_data.py
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/manager/cost_report_data_manager.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/currency_manager.py
  src/spaceone/cost_analysis/manager/email_manager.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/model/__init__.py
  src/spaceone/cost_analysis/model/cost_report/__init__.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/request.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/model/cost_report_config/__init__.py
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/model/cost_report_config/request.py
  src/spaceone/cost_analysis/model/cost_report_config/response.py
  src/spaceone/cost_analysis/model/cost_report_data/__init__.py
  src/spaceone/cost_analysis/model/cost_report_data/database.py
  src/spaceone/cost_analysis/model/cost_report_data/request.py
  src/spaceone/cost_analysis/model/cost_report_data/response.py
  src/spaceone/cost_analysis/service/__init__.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
  src/spaceone/cost_analysis/template/cost_report_en.html
  src/spaceone/cost_analysis/template/cost_report_jp.html
  src/spaceone/cost_analysis/template/cost_report_ko.html
Labels: enhancement

#175 Fix created_at field type
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/model/cost_report_data/response.py
Labels: bug

#176 Add language field at CostReport
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#177 Remove language at CostReport
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#178 Fix typo parameter order
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#179 Add exchange currency function
  src/spaceone/cost_analysis/connector/currency_connector.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/currency_manager.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#180 Fix tuple typo
  src/spaceone/cost_analysis/connector/currency_connector.py
  src/spaceone/cost_analysis/manager/currency_manager.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
Labels: bug

#182 Modify filter to get send cost report recipients
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/model/cost_report_config/request.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#184 Get exchange currency by all currencies
  src/spaceone/cost_analysis/connector/currency_connector.py
  src/spaceone/cost_analysis/manager/currency_manager.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#186 Add default EMAIL_SERVICE_NAME
  src/spaceone/cost_analysis/conf/global_conf.py
Labels: enhancement
