Repository cloudforet-io/cost-analysis, pull requests merged in 2025-04, with the labels that each got.

#335 Add budget_manager_id field for Budget
  src/spaceone/cost_analysis/manager/budget_manager.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/model/budget/database.py
  src/spaceone/cost_analysis/model/budget/request.py
  src/spaceone/cost_analysis/model/budget/response.py
  src/spaceone/cost_analysis/service/budget_service.py
Labels: enhancement, pass/signedoff

#336 Implement budget utilization rate update scheduler and related tasks
  deploy/helm/Chart.yaml
  deploy/helm/values.yaml
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/interface/task/v1/budget_update_scheduler.py
  src/spaceone/cost_analysis/interface/task/v1/cost_report_run_scheduler.py
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
  src/spaceone/cost_analysis/manager/budget_manager.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/service/budget_service.py
Labels: enhancement, pass/signedoff

#337 Add convert model decorator at stat api
  src/spaceone/cost_analysis/service/budget_service.py
Labels: bug

#338 Add budget year field and modify budget update scheduler
  src/spaceone/cost_analysis/error/budget.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/model/budget/database.py
  src/spaceone/cost_analysis/model/budget/request.py
  src/spaceone/cost_analysis/model/budget/response.py
  src/spaceone/cost_analysis/model/budget_usage/database.py
  src/spaceone/cost_analysis/service/budget_service.py
Labels: bug, enhancement, pass/signedoff

#339 Modify budget and budget usage index order
  src/spaceone/cost_analysis/manager/budget_manager.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/model/budget/database.py
  src/spaceone/cost_analysis/model/budget/request.py
  src/spaceone/cost_analysis/model/budget_usage/request.py
  src/spaceone/cost_analysis/model/unified_cost/database.py
  src/spaceone/cost_analysis/service/budget_service.py
  src/spaceone/cost_analysis/service/budget_usage_service.py
Labels: enhancement, pass/signedoff

#341 Enhance budget notification logic
  src/spaceone/cost_analysis/interface/task/v1/budget_update_scheduler.py
  src/spaceone/cost_analysis/manager/budget_manager.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/manager/email_manager.py
  src/spaceone/cost_analysis/model/budget/database.py
  src/spaceone/cost_analysis/service/budget_service.py
  src/spaceone/cost_analysis/template/budget_usage_alert_en.html
  src/spaceone/cost_analysis/template/budget_usage_alert_ko.html
Labels: enhancement, pass/signedoff

#342 Modify cost report run scheduler class name
  src/spaceone/cost_analysis/interface/task/v1/budget_update_scheduler.py
  src/spaceone/cost_analysis/interface/task/v1/cost_report_run_scheduler.py
Labels: bug

#343 Update workflow to use Ubuntu 22.04
  .github/workflows/dispatch_daily_build.yaml
Labels: enhancement, pass/signedoff

#344 Add `budget_manageR_id` element for budget stat keyword filter query
  src/spaceone/cost_analysis/service/budget_service.py
Labels: enhancement, pass/signedoff

#345 Add error handling for unverified budget managers and update notification checks
  src/spaceone/cost_analysis/error/budget.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/service/budget_service.py
Labels: enhancement

#346 Enhance budget management with optional workspace_id and refactor budget usage notification logic
  src/spaceone/cost_analysis/manager/budget_manager.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/service/budget_service.py
Labels: bug, enhancement, pass/signedoff

#347 Add budget state field and improve budget usage update logic
  src/spaceone/cost_analysis/error/budget.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/model/budget/database.py
  src/spaceone/cost_analysis/model/budget/request.py
  src/spaceone/cost_analysis/model/budget/response.py
  src/spaceone/cost_analysis/service/budget_service.py
Labels: pass/signedoff

#348 Implement budget state update job scheduling and enhance budget state management
  src/spaceone/cost_analysis/error/budget.py
  src/spaceone/cost_analysis/interface/task/v1/budget_update_scheduler.py
  src/spaceone/cost_analysis/manager/budget_manager.py
  src/spaceone/cost_analysis/service/budget_service.py
Labels: enhancement

#349 Add service_account_id field to budget usage model
  src/spaceone/cost_analysis/model/budget_usage/database.py
Labels: bug

#350 Add service_account_id field to budget usage list request query filter
  src/spaceone/cost_analysis/model/budget_usage/request.py
  src/spaceone/cost_analysis/service/budget_usage_service.py
Labels: bug, pass/signedoff

#351 Revert "Migrate cost report services to UnifiedCost model"
  src/spaceone/cost_analysis/interface/grpc/cost_report.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
  src/spaceone/cost_analysis/plugin/data_source/model/cost_request.py
  src/spaceone/cost_analysis/service/__init__.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: fail/signedoff

#352 Add Unified cost analysis with domain_id filtering and project_group_id
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
Labels: enhancement

#353 Add error handling for duplicated budget thresholds
  src/spaceone/cost_analysis/error/budget.py
  src/spaceone/cost_analysis/service/budget_service.py
Labels: enhancement

#354 Update workspace_id field to be optional when get budget info
  src/spaceone/cost_analysis/model/budget/request.py
Labels: enhancement
