Repository cloudforet-io/cost-analysis, pull requests merged in 2025-05, with the labels that each got.

#360 implement of ReportAdjustmentPolicy
  .gitignore
  src/spaceone/cost_analysis/error/__init__.py
  src/spaceone/cost_analysis/error/report_adjustment.py
  src/spaceone/cost_analysis/error/report_adjustment_policy.py
  src/spaceone/cost_analysis/interface/grpc/__init__.py
  src/spaceone/cost_analysis/interface/grpc/report_adjustment.py
  src/spaceone/cost_analysis/interface/grpc/report_adjustment_policy.py
  src/spaceone/cost_analysis/manager/__init__.py
  src/spaceone/cost_analysis/manager/cost_report/__init__.py
  src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
  src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/manager/cost_report_data_manager.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/data_source_account_manager.py
  src/spaceone/cost_analysis/manager/data_source_manager.py
  src/spaceone/cost_analysis/manager/report_adjustment_manager.py
  src/spaceone/cost_analysis/manager/report_adjustment_policy_manager.py
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
  src/spaceone/cost_analysis/model/__init__.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/model/cost_report_config/request.py
  src/spaceone/cost_analysis/model/cost_report_config/response.py
  src/spaceone/cost_analysis/model/cost_report_data/database.py
  src/spaceone/cost_analysis/model/cost_report_data/response.py
  src/spaceone/cost_analysis/model/report_adjustment/__init__.py
  src/spaceone/cost_analysis/model/report_adjustment/database.py
  src/spaceone/cost_analysis/model/report_adjustment/request.py
  src/spaceone/cost_analysis/model/report_adjustment/response.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/__init__.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/database.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/request.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/response.py
  src/spaceone/cost_analysis/service/__init__.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
  src/spaceone/cost_analysis/service/report_adjustment_policy_service.py
  src/spaceone/cost_analysis/service/report_adjustment_service.py
Labels: pass/signedoff

#363 Enhance cost report generation with project name mapping and metadata handling
  src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
  src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/database.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/request.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/response.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
  src/spaceone/cost_analysis/service/report_adjustment_policy_service.py
Labels: pass/signedoff

#365 Update currency_end_date to use the instance's currency_date
  src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
Labels: pass/signedoff

#359 [Pull Request] Merged Refactoring codes to Master
  .github/workflows/dispatch_daily_build.yaml
  deploy/helm/Chart.yaml
  deploy/helm/values.yaml
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/connector/datasource_plugin_connector.py
  src/spaceone/cost_analysis/error/budget.py
  src/spaceone/cost_analysis/info/__init__.py
  src/spaceone/cost_analysis/info/common_info.py
  src/spaceone/cost_analysis/info/cost_info.py
  src/spaceone/cost_analysis/info/cost_query_set_info.py
  src/spaceone/cost_analysis/info/data_source_info.py
  src/spaceone/cost_analysis/info/data_source_rule_info.py
  src/spaceone/cost_analysis/info/job_info.py
  src/spaceone/cost_analysis/info/job_task_info.py
  src/spaceone/cost_analysis/interface/task/v1/budget_update_scheduler.py
  src/spaceone/cost_analysis/interface/task/v1/cost_report_run_scheduler.py
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
  src/spaceone/cost_analysis/manager/budget_manager.py
  src/spaceone/cost_analysis/manager/budget_usage_manager.py
  src/spaceone/cost_analysis/manager/cost_manager.py
  src/spaceone/cost_analysis/manager/cost_query_set_manager.py
  src/spaceone/cost_analysis/manager/data_source_plugin_manager.py
  src/spaceone/cost_analysis/manager/data_source_rule_manager.py
  src/spaceone/cost_analysis/manager/email_manager.py
  src/spaceone/cost_analysis/manager/identity_manager.py
  src/spaceone/cost_analysis/manager/job_manager.py
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
  src/spaceone/cost_analysis/model/budget/database.py
  src/spaceone/cost_analysis/model/budget/request.py
  src/spaceone/cost_analysis/model/budget/response.py
  src/spaceone/cost_analysis/model/budget_usage/database.py
  src/spaceone/cost_analysis/model/budget_usage/request.py
  src/spaceone/cost_analysis/model/budget_usage/response.py
  src/spaceone/cost_analysis/model/cost_query_set/response.py
  src/spaceone/cost_analysis/model/data_source_account/request.py
  src/spaceone/cost_analysis/model/data_source_model.py
  src/spaceone/cost_analysis/model/data_source_rule/request.py
  src/spaceone/cost_analysis/model/data_source_rule/response.py
  src/spaceone/cost_analysis/model/unified_cost/database.py
  src/spaceone/cost_analysis/service/__init__.py
  src/spaceone/cost_analysis/service/budget_service.py
  src/spaceone/cost_analysis/service/budget_usage_service.py
  src/spaceone/cost_analysis/service/cost_query_set_service.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
  src/spaceone/cost_analysis/service/cost_service.py
  src/spaceone/cost_analysis/service/data_source_account_service.py
  src/spaceone/cost_analysis/service/data_source_rule_service.py
  src/spaceone/cost_analysis/service/data_source_service.py
  src/spaceone/cost_analysis/service/job_service.py
  src/spaceone/cost_analysis/service/job_task_service.py
  src/spaceone/cost_analysis/service/unified_cost_service.py
  src/spaceone/cost_analysis/template/budget_usage_alert_en.html
  src/spaceone/cost_analysis/template/budget_usage_alert_ko.html
Labels: enhancement, fail/signedoff

#366 merge & refactor : merge from cloudforet master & refactoring added code
  .github/workflows/dispatch_daily_build.yaml
  .gitignore
  src/spaceone/cost_analysis/error/__init__.py
  src/spaceone/cost_analysis/error/cost_report_config.py
  src/spaceone/cost_analysis/error/report_adjustment.py
  src/spaceone/cost_analysis/error/report_adjustment_policy.py
  src/spaceone/cost_analysis/interface/grpc/__init__.py
  src/spaceone/cost_analysis/interface/grpc/report_adjustment.py
  src/spaceone/cost_analysis/interface/grpc/report_adjustment_policy.py
  src/spaceone/cost_analysis/manager/__init__.py
  src/spaceone/cost_analysis/manager/cost_report/__init__.py
  src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
  src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/manager/cost_report_data_manager.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/data_source_account_manager.py
  src/spaceone/cost_analysis/manager/data_source_manager.py
  src/spaceone/cost_analysis/manager/report_adjustment_manager.py
  src/spaceone/cost_analysis/manager/report_adjustment_policy_manager.py
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
  src/spaceone/cost_analysis/model/__init__.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/model/cost_report_config/request.py
  src/spaceone/cost_analysis/model/cost_report_config/response.py
  src/spaceone/cost_analysis/model/cost_report_data/database.py
  src/spaceone/cost_analysis/model/cost_report_data/response.py
  src/spaceone/cost_analysis/model/report_adjustment/__init__.py
  src/spaceone/cost_analysis/model/report_adjustment/database.py
  src/spaceone/cost_analysis/model/report_adjustment/request.py
  src/spaceone/cost_analysis/model/report_adjustment/response.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/__init__.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/database.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/request.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/response.py
  src/spaceone/cost_analysis/service/__init__.py
  src/spaceone/cost_analysis/service/cost_report_config_service.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
  src/spaceone/cost_analysis/service/report_adjustment_policy_service.py
  src/spaceone/cost_analysis/service/report_adjustment_service.py
Labels: fail/signedoff

#369 Refactor report adjustment policy to use query parameters and update scope handling
  src/spaceone/cost_analysis/model/report_adjustment_policy/request.py
  src/spaceone/cost_analysis/model/report_adjustment_policy/response.py
  src/spaceone/cost_analysis/service/report_adjustment_policy_service.py
  src/spaceone/cost_analysis/service/report_adjustment_service.py
Labels: enhancement, pass/signedoff

#370 Update 'unit' choices in ReportAdjustment model to include 'PERCENT' instead of 'PERCENTAGE'
  src/spaceone/cost_analysis/model/report_adjustment/database.py
Labels: bug

#371 Update status choices in CostReport model to include 'ADJUSTING and 'DONE'
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/request.py
Labels: enhancement

#372 Rename 'workspace_name' to 'name' in cost report service and related files
  src/spaceone/cost_analysis/model/cost_report/request.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement, pass/signedoff

#373 fix: fix CostReport & UnifiedCost Logic
  src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
  src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
  src/spaceone/cost_analysis/manager/cost_report_manager.py
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: fail/signedoff

#376 Rename 'workspace_name' to 'name' in service, database, and request/response models
  src/spaceone/cost_analysis/model/cost_report/database.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/model/cost_report_data/request.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: enhancement

#377 Refactor cost report handling to use 'name' instead of 'workspace_name' and improve currency management
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/connector/currency_connector.py
  src/spaceone/cost_analysis/manager/cost_report/adjustment_policy_applier.py
  src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
  src/spaceone/cost_analysis/manager/cost_report_config_manager.py
  src/spaceone/cost_analysis/manager/cost_report_data_manager.py
  src/spaceone/cost_analysis/manager/email_manager.py
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
  src/spaceone/cost_analysis/model/cost_report/response.py
  src/spaceone/cost_analysis/model/cost_report_config/database.py
  src/spaceone/cost_analysis/model/cost_report_config/request.py
  src/spaceone/cost_analysis/model/cost_report_config/response.py
  src/spaceone/cost_analysis/model/cost_report_data/database.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
  src/spaceone/cost_analysis/template/cost_report_en.html
  src/spaceone/cost_analysis/template/cost_report_ja.html
  src/spaceone/cost_analysis/template/cost_report_ko.html
Labels: enhancement

#379 Add support for WAREHOUSE data source type and integrate Databricks
  pkg/pip_requirements.txt
  src/spaceone/cost_analysis/conf/global_conf.py
  src/spaceone/cost_analysis/connector/databricks_connector.py
  src/spaceone/cost_analysis/manager/cost_manager.py
  src/spaceone/cost_analysis/manager/cost_report/cost_report_format_generator.py
  src/spaceone/cost_analysis/model/data_source/request.py
  src/spaceone/cost_analysis/model/data_source_model.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
  src/spaceone/cost_analysis/service/data_source_service.py
Labels: enhancement, pass/signedoff

#380 Update DatabricksConnector to use 'billed_month' for date formatting and change GROUP BY clause to 'ALL'
  src/spaceone/cost_analysis/connector/databricks_connector.py
Labels: pass/signedoff
