Repository cloudforet-io/cost-analysis, pull requests merged in 2025-02, with the labels that each got.

#318 Correct logic for manual duplicate job time check
  src/spaceone/cost_analysis/service/job_service.py
Labels: enhancement

#320 Fix workspace scope change cost data rule param
  src/spaceone/cost_analysis/manager/data_source_account_manager.py
Labels: bug

#319 add: add schedule field to DataSource
  src/spaceone/cost_analysis/info/data_source_info.py
  src/spaceone/cost_analysis/interface/grpc/data_source.py
  src/spaceone/cost_analysis/interface/task/v1/data_source_sync_scheduler.py
  src/spaceone/cost_analysis/model/data_source/request.py
  src/spaceone/cost_analysis/model/data_source/response.py
  src/spaceone/cost_analysis/model/data_source_model.py
  src/spaceone/cost_analysis/service/data_source_service.py
  src/spaceone/cost_analysis/service/job_service.py
Labels: fail/signedoff

#321 Update query filters to use schedule.state and include workspace…
  src/spaceone/cost_analysis/manager/cost_manager.py
  src/spaceone/cost_analysis/manager/data_source_rule_manager.py
  src/spaceone/cost_analysis/service/cost_report_data_service.py
  src/spaceone/cost_analysis/service/cost_report_serivce.py
Labels: bug

#324 Fix yearly unified cost missing cache key error
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
Labels: bug

#325 Recover unified cost cache
  src/spaceone/cost_analysis/manager/unified_cost_manager.py
Labels: enhancement

#326 Modify delete unified cost logic about not exist workspace
  src/spaceone/cost_analysis/service/unified_cost_service.py
Labels: bug
