Repository cloudforet-io/cost-analysis, pull requests merged in 2025-01, with the labels that each got.

#311 refactor: refactor cost sync job
  src/spaceone/cost_analysis/manager/data_source_rule_manager.py
  src/spaceone/cost_analysis/service/job_service.py
Labels: pass/signedoff

#314 Add task_changed field at job task and modify cost index
  src/spaceone/cost_analysis/manager/job_task_manager.py
  src/spaceone/cost_analysis/model/cost_model.py
  src/spaceone/cost_analysis/model/job_task_model.py
  src/spaceone/cost_analysis/plugin/data_source/model/job_response.py
  src/spaceone/cost_analysis/service/job_service.py
Labels: enhancement, pass/signedoff

#315 Fix type error when get changed value at job task
  src/spaceone/cost_analysis/interface/task/v1/unified_cost_run_scheduler.py
  src/spaceone/cost_analysis/service/job_service.py
Labels: bug
